### ISSUE TITLE
gtkmm 4.0 does not build

### ISSUE THREAD

**Issue by kamarya** [AlexB67/CairoPlot#1]
I assume you have not ported this amazing library to version 4.0 yet.

**Comment by AlexB67** [comment]
I have indeed ported it  :) but there are a few drawbacks which stopped me uploading it so far. GTK4 does not work on wayland/nvidia. That's a GTK Nvidia issue, not mine. There were a few additions I didn't finish yet, busy with other things. 

If you want the source badly enough lemme know. I'll upload it (with the above caveats)

I am just waiting for GTK to sort out some bugs before I can rubber stamp it.

Cheers :)

**Comment by kamarya** [comment]
yes please put it on a branch and I will give it a try

**Comment by AlexB67** [comment]
Hi, 
I created a branch. cairopot-gtkmm4. O' course you'll need to build gtmm4 yourself. I recommend to build against at least gtk4.0.3. 

I used:
cairomm-1.16
pango 2.48
glibmm2.68
gtkmm4.0 or later.

Cheers :)
